// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package mysql

var TableNames = struct {
	ArchiveTagMappings string
	Archives           string
	Sites              string
	Tags               string
	Tokens             string
	Users              string
	WebPages           string
}{
	ArchiveTagMappings: "archive_tag_mappings",
	Archives:           "archives",
	Sites:              "sites",
	Tags:               "tags",
	Tokens:             "tokens",
	Users:              "users",
	WebPages:           "web_pages",
}
