-- +migrate Up
-- MySQL Script generated by MySQL Workbench
-- Thu Nov 12 00:15:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema giregi_rip
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema giregi_rip
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `giregi_rip` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `giregi_rip` ;

-- -----------------------------------------------------
-- Table `giregi_rip`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `giregi_rip`.`users` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `uid` VARCHAR(100) NOT NULL COMMENT 'SSO - UID',
  `is_admin` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '운영자 계정 여부',
  `email` VARCHAR(250) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uid` (`uid` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = '사용자';


-- -----------------------------------------------------
-- Table `giregi_rip`.`tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `giregi_rip`.`tokens` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL,
  `token` VARCHAR(200) NOT NULL,
  `user_agent` VARCHAR(255) NULL DEFAULT NULL,
  `expire_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `tokens_user_id_users_id_foreign` (`user_id` ASC),
  CONSTRAINT `tokens_user_id_users_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `giregi_rip`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = '로그인 Token';


-- -----------------------------------------------------
-- Table `giregi_rip`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `giregi_rip`.`tags` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_tags_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_tags_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `giregi_rip`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = '태그';


-- -----------------------------------------------------
-- Table `giregi_rip`.`sites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `giregi_rip`.`sites` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL COMMENT '사이트 이름',
  `domain` VARCHAR(250) NOT NULL COMMENT '사이트 URL',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = '사이트';


-- -----------------------------------------------------
-- Table `giregi_rip`.`web_pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `giregi_rip`.`web_pages` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `site_id` BIGINT(20) NOT NULL,
  `url` VARCHAR(250) NOT NULL COMMENT '웹페이지 URL',
  `title` VARCHAR(100) NULL COMMENT '웹페이지 제목',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `fk_web_pages_sites1_idx` (`site_id` ASC),
  CONSTRAINT `fk_web_pages_sites1`
    FOREIGN KEY (`site_id`)
    REFERENCES `giregi_rip`.`sites` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = '웹페이지';


-- -----------------------------------------------------
-- Table `giregi_rip`.`archives`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `giregi_rip`.`archives` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `web_page_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `memo` VARCHAR(200) NOT NULL COMMENT '유형',
  `status` VARCHAR(25) NOT NULL COMMENT 'archive.org - job status',
  `job_id` VARCHAR(250) NOT NULL COMMENT 'archive.org - job ID',
  `wayback_id` VARCHAR(250) NOT NULL COMMENT 'archive.org - archive ID',
  `summary` JSON NOT NULL COMMENT '요약 정보',
  `public` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '공개여부',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `fk_archive_web_pages1_idx` (`web_page_id` ASC),
  INDEX `fk_archive_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_archive_web_pages1`
    FOREIGN KEY (`web_page_id`)
    REFERENCES `giregi_rip`.`web_pages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_archive_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `giregi_rip`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = '아카이브';


-- -----------------------------------------------------
-- Table `giregi_rip`.`archive_tag_mappings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `giregi_rip`.`archive_tag_mappings` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `tag_id` BIGINT(20) NOT NULL,
  `archive_id` BIGINT(20) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `fk_web_page_tag_mappings_tags1_idx` (`tag_id` ASC),
  INDEX `fk_web_page_tag_mappings_archive1_idx` (`archive_id` ASC),
  CONSTRAINT `fk_web_page_tag_mappings_tags1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `giregi_rip`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_web_page_tag_mappings_archive1`
    FOREIGN KEY (`archive_id`)
    REFERENCES `giregi_rip`.`archives` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = '아카이브 - 태그';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
